### DISCUSSION TITLE
\cancel argument is blank

### DISCUSSION THREAD

**Discussion by willymcallister** [KaTeX/KaTeX#2512] [Q&A] [answered]
The argument to  \cancel is showing up blank. I changed from Katex 10.0.0 to 12.0.0 on my local MacBook. Same rendering in both. The code renders properly at katex.org. I'm using Katex in a Jekyll/Github site. Here's an example [article](https://spinningnumbers.org/a/line-of-charge2.html#electric-field-from-a-line-of-charge) (this is being rendered by 10.0.0). Scroll down a little to see the blank cancellations. Any tips on how to debug this?

Sample equation:
`$\dfrac{dx}{r^2} = \dfrac{\blueD{\cancel{a}\, \cancel{\sec^2 \theta} \,d\theta}}{\maroonD{a^{\cancel{2}} \, \cancel{\sec^2 \theta}}}$`

<img width="820" alt="Screen Shot 2020-09-12 at 5 40 54 PM" src="https://user-images.githubusercontent.com/17035787/93007653-edc31d80-f51f-11ea-9bb2-42c13eefd05e.png">
<img width="214" alt="Screen Shot 2020-09-12 at 5 41 14 PM" src="https://user-images.githubusercontent.com/17035787/93007654-ef8ce100-f51f-11ea-9ad4-9e7d58f4bb0a.png">

**Comment by ylemkimon** [comment, marked as answer]
The `background-color` and `border-radius` of SVGs are overridden by https://spinningnumbers.org/assets/main.css:
```css
svg {
    background-color: var(--img-background-color);
    opacity: 1.0;
    border-radius: 4px;
}
```
You can make the rule above more specific or add following:
```css
.katex svg {
    background-color: initial;
    border-radius: initial;
}
```
