### DISCUSSION TITLE
Equations in colored box with light/dark mode

### DISCUSSION THREAD

**Discussion by willymcallister** [KaTeX/KaTeX#2553] [Show and tell]
I posted this question in #2531.
"With \colorbox the color specification appears to be hard coded. The allowable arguments are #hexcodes and standard HTML color names. Can you think of a way to make the color responsive to dark/light mode?"

@edemaine made this suggestion,
 ...  \htmlClass is probably what you're looking for. See https://katex.org/docs/supported.html#html

`\htmlClass` seemed over my head. I worked out a different way, using a new class in [main.scss](https://github.com/willymcallister/willymcallister.github.io/blob/master/assets/main.scss),

```css
 .colorbox {  
  background: var(--box-color);   
  display: inline-block;  
}
```

The background color, --box-color, is sensitive to dark/light mode, as defined at the top of the same main.scss file,

```scss
html {  
  --box-color: #94fff5;  

@media (prefers-color-scheme: dark) {  
  html {  
  --box-color: #144f44;                 
  }  
}  
```
 
And the last step is to reference the new class by appending `{: .colorbox :}` on the line after the equation in a markdown file,

```markdown
$\boxed{v_{tot} = (\text V_0 - \text V_\text S)\,e^{-t/\text{RC}} + \text V_\text S}$
{: .colorbox :}
```

The result,

<img width="309" alt="Screen Shot 2020-09-28 at 4 12 49 PM" src="https://user-images.githubusercontent.com/17035787/94495436-9cb15b80-01a6-11eb-9d58-47407fc190ab.png">
<img width="297" alt="Screen Shot 2020-09-28 at 4 13 13 PM" src="https://user-images.githubusercontent.com/17035787/94495440-9d49f200-01a6-11eb-832f-ef20198e23ca.png">
