### ISSUE TITLE
Support for leqno and fleqn rendering options

### ISSUE THREAD

**Issue by willymcallister** [KaTeX/KaTeX#1776]
In katex 0.10+ is it possible to render a left-justified equation on its own line and include a \tag{} or \tag*{}?

**Comment by edemaine** [comment]
Thanks! I'd been meaning to add an issue for this.

The fix for now is to add this CSS to your page:
```css
.katex-display > .katex > .katex-html > .tag !important { left: 0; right: auto; }
```

We should add this to the documentation, or add an `leqno` option to the options list. (In LaTeX, this is triggered via `\usepackage[leqno]{amsmath}`.)
