### ISSUE TITLE
Display block instead of inline-block and equation numbering

### ISSUE THREAD

**Issue by tlienart** [KaTeX/KaTeX#1785]
Hello,

I use the following bit of CSS to display numbers after equations: 

```CSS
.katex-display::after {
    counter-increment: eqnum;
    content: "(" counter(eqnum) ")";
    position: relative;
    float: right; }
```

This used to work just fine but with the new release, the number now appears below the equation:

![screen shot 2018-11-20 at 7 02 01 pm](https://user-images.githubusercontent.com/10897531/48759337-e69da080-ecf6-11e8-8703-572fd201c1f0.png)

This can be fixed by setting

```css
.katex-display > .katex {
    display: inline-block;
}
```

but I imagine it was changed to `display: block` for a reason? So my question is, can I expect anything not working well if I use the fix above, and/or is there a better workaround?

Thanks!

(PS: I use `auto-render` and the bundle from `v0.10.0`)
