### ISSUE TITLE
Use font-display: swap to prevent invisible text on load

### ISSUE THREAD

**Issue by yawnoc** [KaTeX/KaTeX#2242]
Google PageSpeed Insights suggests that I should "ensure text remains visible during webfont load".

For KaTeX this would simply involve including [`font-display: swap;`][mdn-font-face] in all of the `@font-face` entries in `katex.css`.

I think this a good idea, but how would we then cater for people who *don't* want to temporarily show a fallback font?

[mdn-font-face]: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#Values

**Comment by edemaine** [comment]
I've always wondered why my math appears blank on initial page load. 😄 I'm honestly not sure which behavior would feel best, but `swap` behavior is probably less surprising. I believe you can customize this now with the following CSS:
```css
.katex { font-display: swap; }
```
If we added a rule to base KaTeX, it could still be overridden via
```css
.katex { font-display: block !important; }
```
Either way, this should probably be documented. The question is whether to change the default... Other votes would be welcome!

**Comment by mbourne** [comment]
Google's page speed suggestion, in general, is to use swap, and this is not the default for all browsers: https://developers.google.com/web/updates/2016/02/font-display

Personally, I hate text jumping around as fonts are loading, but I'm not a big fan of the flash of "wrong" font with swap, either.

It may be best to work towards an option where if the font is already in cache, then use block; if not, use swap. 

I conducted some experiments where I did lazy-load for math processing, making sure the above-the-fold content had most-used fonts ready to roll (using preload) and then loaded other fonts as the user scrolled down the page. Probably too fiddly for default KaTeX behavior, but something the browsers should do for us, I feel.

**Comment by yawnoc** [comment]
> I believe you can customize this now with the following CSS:
> ```css
> .katex { font-display: swap; }
> ```

Hmm, that doesn't validate:
> 1 | `.katex` | Property `font-display` doesn't exist : `swap`

I think `font-display` is only allowed when the font is loaded in the `@font-face` at-rule... so we'd need to provide 2 different versions of `katex.css` to offer the choice.

**Comment by rabinadk1** [comment]
You need to specify it in the fonts CSS like
```css
@font-face {
  font-family: 'Lato';
  font-style: italic;
  font-weight: 100;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/lato/v17/S6u-w4BMUTPHjxsIPx-mPCLQ7A.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```
It is better to show things in Times New Roman font, which is the default fallback font than to make users wait for the font to load and display nothing.
