### ISSUE TITLE
Can we solve \tag overlap with flexboxes?

### ISSUE THREAD

**Issue by ig-perez** [KaTeX/KaTeX#3066]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Nota bene**: Please forgive me if my ignorance in Katex internals is making me propose something dumb.

**Describe the bug:**
Hi guys, thanks for maintaining this package!

As you can imagine for the tittle of this issue I'm struggling with the `\tag` overlap when displaying web pages in mobile devices. For example this equation:
![image](https://user-images.githubusercontent.com/33359427/120908350-f5d36800-c62e-11eb-8219-9594a011e4ee.png)

I was trying to solve this by overriding the CSS with this:

```css
    .katex-html {
      display: flex !important;
      flex-direction: row;
      flex-wrap: nowrap;
      justify-content: space-between;
      align-items: baseline;
      overflow-x: auto;
    }

    .katex-html .base {
      display: inline !important;
    }

    .katex-html .tag {
      display: inline !important;
      position: relative !important;
      margin-left: var(--margin-small);
    }
```

And it works!:
![image](https://user-images.githubusercontent.com/33359427/120908360-27e4ca00-c62f-11eb-8608-77d74e4cb12e.png)
![image](https://user-images.githubusercontent.com/33359427/120908533-c9205000-c630-11eb-8e12-90e28168c10c.png)

Sadly, the inline math expressions break:
Before:
![image](https://user-images.githubusercontent.com/33359427/120908407-7f833580-c62f-11eb-88ae-2fb62469901e.png)

After: 
![image](https://user-images.githubusercontent.com/33359427/120908413-92960580-c62f-11eb-8745-68569e2429dd.png)

I think it is because both, the inline and block styling, share the same CSS classes. So I want to ask you, what if you use a different CSS class for inline and block styling?

If we have different classes, we can leave inline styling as it is and use the code snippet above just for block equations.

Actually, it might be possible to just add an extra class indicator when inserting a block element, something like `katex-block`at the end of the `span` class property, like this:

![image](https://user-images.githubusercontent.com/33359427/120908720-c7578c00-c632-11eb-8480-4ee1b2efabb7.png)

In this way `katex-block`will have the CSS code snnipet above.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
$$
\begin{aligned}
J(\theta) = - \frac{1}{T} \log L(\theta) = - \frac{1}{T} \sum_{t=1}^{T} \sum_{-m \leq j \leq m} \log P(w_{t+j} | w_t; \theta); j \neq 0
\tag{2}
\end{aligned}
$$
```

**Expected behavior:**
The equation number should appear at the right of the equation, not over it.

**Environment (please complete the following information):**
 - KaTeX Version: 0.13.11
 - Device: Android Mobile device. Can also be shown with Firefox's Responsive Design Mode
 - OS: Android, Linux
 - Browser: Firefox 88.0.1 (64-bit), Chromium Version 90.0.4430.212 (Developer Build) Fedora Project (64-bit)

Thanks!
