### ISSUE TITLE
[accessibility] CSS forced colors mode (e.g., Windows high contrast) requires updated handling

### ISSUE THREAD

**Issue by GeeLaw** [KaTeX/KaTeX#4049]
Previous issue is #716. Related #3974.

**Do not try solving this issue now.** I think CSS working group needs to clarify certain points before we can reliably support forced-colors mode.

## Steps to reproduce

Use MSEdge 136.0.3240.50 (Official build) (64-bit) Chromium version 136.0.7103.49 on Windows 11 (24H2 if that matters) to visit KaTeX website, and enter

```
\begin{aligned}
&
\f\relax{x} = \int_{-\infty}^\infty
    \f\hat\xi\,e^{2 \pi i \xi x}
    \,d\xi
\\&
{\color{red}\text{ Hey}}
\\&
\textcolor{blue}{F=ma}
\textcolor{#228B22}{F=ma}
\\&
\colorbox{aqua}{$F=ma$}
\fcolorbox{red}{aqua}{$F=ma$}
\end{aligned}
```

we see

![Image](https://github.com/user-attachments/assets/92af953c-0b0e-45ae-8bd7-e4fb48f50cf7)

This is expected. Now switch to a high contrast theme, e.g., "Aquatic", we see

![Image](https://github.com/user-attachments/assets/0274e3c4-c80f-47bb-833f-013783a825e2)

where the issue #716 reappears --- formula components cut into each other. Also, the text/box colors are incorrect (although what color it should be is debatable).

## Analysis

For fashion reasons, Microsoft decided to unsupport `-ms-high-contrast` media query and `-ms-high-contrast-adjust` property: https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/

**Mandatory rant:** There's almost no cost to continue supporting these rules. It appears fashion is more important than accessibility to Microsoft.

The standard is `forced-colors` media query and `forced-color-adjust` property. According to [the documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/forced-color-adjust), there are 3 choices of `forced-color-adjust`:

- `auto`, which yields the screenshot;
- `none`, which would create other incorrect results;
- `preserve-parent-color`, which behaves crazy and is not what the documentation says.

**Why `preserve-parent-color` is not good for now.** If we choose `preserve-parent-color`, the descendants will:

1. Inherit the color from the parent element, which is desired and will be the correct color (user-specific text color by default).
2. Lose the background --- this is also what we want, but losing of background is **NOT** in the documentation.

We don't want to rely on incorrectly documented or implemented behaviors.

**One possible solution, why it doesn't work.** Suppose

1. In forced-colors mode, we want the formula components to not cut each other.
2. Normally, the formula should follow the surrounding text color, after forced-colors adjustment.
3. (Big assumption.) If a user uses special colors, then that part of the formula should be highlighted.

Then the idea is as follows:

1. Query for `forced-colors` media, when active, set `forced-color-adjust: none`.
2. Adjust the colors ourselves using inheritance.
3. Adjust the colored part to use highlight colors.

Note that we cannot use `HighlightText` and `Highlight` (background) or `MarkText` and `Mark` (background) to highlight the color things, because the two colors must be used together to ensure contrast. However, normally text are on `Canvas` (background) and have `CanvasText` color. The only colors that contrast both `Canvas` and `CanvasText` is `LinkText`, `ActiveText`, and `VisitedText`. It's the best to use `ActiveText`:

1. In the examples, those three colors are the same, so they're tie from this perspective.
2. If a user sets them different, the only way to differentiate non-link `LinkText`-/`VisitedText`-colored text from links, is to hover or try focusing them.
3. If a user sets them different, by not doing any action on the page, the user knows any text that's `ActiveText` must represent a highlighted formula --- this is a learnable and no-interaction differentiable option.

One possible implementation:

```css
@media (forced-colors: active)
{
  .katex
  {
    /* If we don't override the colors again,
    ** the child elements will inherit the custom values,
    ** not the forced values.
    ** I'm not sure if that is a bug or feature. */
    forced-color-adjust: none;
    color: CanvasText;
    background: Canvas;
  }
  .katex *
  {
    forced-color-adjust: none;
    color: inherit;
    background: transparent !important;
  }
  /* !important to override attribute style */
  .katex, .katex *
  {
    border-color: currentcolor !important;
    outline-color: currentcolor !important;
    text-decoration-color: currentcolor !important;
    text-emphasis-color: currentcolor !important;
  }
  .katex .colorbox, .katex .fcolorbox,
  .katex span[style*="color"],
  .katex span:has(>.fcolorbox) + span,
  .katex span:has(>.colorbox) + span
  {
    color: ActiveText !important;
  }
}
```

After applying the aforementioned style to KaTeX website:

![Image](https://github.com/user-attachments/assets/a577f58a-b55e-469d-a9b9-3de247778b26)

**Do not** remove `-ms-high-contrast-adjust: none` etc. There's no harm to keep them there and KaTeX readme says it wants to support IE 11.

## Caveats

1. If a user uses both blue and red and refers to the colored terms, they will not be visible in forced-colors mode.
2. I don't know if forced-colors mode can apply to `print` media.
